apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 5760e4c0b83a2121bb22d86779b619b0cfbb83c1a9d3fcbcab4a33c6f733b2a5
    cni.projectcalico.org/podIP: 10.233.106.230/32
    cni.projectcalico.org/podIPs: 10.233.106.230/32
    kubectl.kubernetes.io/restartedAt: "2025-01-19T16:43:03+03:30"
  creationTimestamp: "2025-02-24T07:26:43Z"
  generateName: harmony-celery-worker-toman-harmony-5fc896f977-
  labels:
    app.kubernetes.io/instance: harmony-celery-worker
    app.kubernetes.io/name: toman-harmony
    pod-template-hash: 5fc896f977
  name: harmony-celery-worker-toman-harmony-5fc896f977-58x2m
  namespace: toman-harmony
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: harmony-celery-worker-toman-harmony-5fc896f977
    uid: ab8e6f8d-5d12-416c-a21a-fdcf3bf9767c
  resourceVersion: "283765711"
  uid: 12cdf5d2-48ae-4bc3-9627-0183128286bc
spec:
  containers:
  - env:
    - name: ENTRYPOINT
      value: celery_worker
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    envFrom:
    - configMapRef:
        name: harmony
    image: registry.qcluster.org/toman/microservices/harmony:47891
    imagePullPolicy: Always
    name: harmony
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 128Mi
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-v7pjw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: gitlab-registry
  nodeName: stage-worker-01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: harmony-celery-worker-toman-harmony
  serviceAccountName: harmony-celery-worker-toman-harmony
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-v7pjw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-02-24T07:26:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-02-24T07:27:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-02-24T07:27:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-02-24T07:26:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e227f7e157e67ad894c50f45c4f372a472e0c7b950df099a41e692665363c441
    image: registry.qcluster.org/toman/microservices/harmony:47891
    imageID: registry.qcluster.org/toman/microservices/harmony@sha256:7d61510675332eed3fd560b5297b4c8082e5d5b3b50f878d0a709e906cf4f940
    lastState: {}
    name: harmony
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-02-24T07:27:00Z"
  hostIP: 172.28.1.110
  phase: Running
  podIP: 10.233.106.230
  podIPs:
  - ip: 10.233.106.230
  qosClass: Burstable
  startTime: "2025-02-24T07:26:43Z"
